# Generated by Django 4.1.1 on 2022-09-06 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_add_slug_to_product'),
    ]

    operations = [
    ]
